### ISSUE TITLE
Problem with RSpamD 2.5

### ISSUE THREAD

**Issue by NaLiJa** [griff/whitelist#22]
Thanks a lot for maintaining the lists. 

Unfortunately I am having a small problem with the latest rspamd version. This configuration part is not understood by the rspmd configuration parser:

whitelist_domains_url {
  name = "Whitelisted Domains";
  urls = [
    "sign+key=f7m4jxua6iwtw5966bhfhxqw6xid758nn6putwb51gum9gmzbeqy+https://whitelist.maven-group.org/lists/combined_rspamd_domains"
  ];
  poll_time = 7d;
}

leads to 
rspamd_config_read: failed to load config: ucl parser error: error while parsing /etc/rspamd/local.d/greylist.conf: line: 10, column: 22 - 'cannot merge an object with an array', character: '{'

Do you perhaps have a fix for this? 
Thanks again for your work and your help!

**Comment by griff** [comment]
I have looked at this and the problem seems to be that you need to place the file in `/etc/rspamd/override.d/greylist.conf` instead of `/etc/rspamd/local.d/greylist.conf`.

This is because the default configuration looks like this:

```
whitelist_domains_url = [
    "$LOCAL_CONFDIR/local.d/greylist-whitelist-domains.inc",
    "$LOCAL_CONFDIR/local.d/maps.d/greylist-whitelist-domains.inc",
  ];
```

And to replace that with one where you specify `poll_time` you need to override it and that is done by placing the file in `/etc/rspamd/override.d` instead.

If you want to keep the existing whitelist files you can just add them to the `urls` key:
```
whitelist_domains_url {
  name = "Whitelisted Domains";
  urls = [
    "sign+key=f7m4jxua6iwtw5966bhfhxqw6xid758nn6putwb51gum9gmzbeqy+https://whitelist.maven-group.org/lists/combined_rspamd_domains",
    "$LOCAL_CONFDIR/local.d/greylist-whitelist-domains.inc",
    "$LOCAL_CONFDIR/local.d/maps.d/greylist-whitelist-domains.inc",
  ];
  poll_time = 7d;
}
```

Since the support for signed remote values has been removed from RSpamD you can also delete the `sign+key=f7m4jxua6iwtw5966bhfhxqw6xid758nn6putwb51gum9gmzbeqy+` prefix and just use the HTTP URL`https://whitelist.maven-group.org/lists/combined_rspamd_domains` since the prefix no longer does anything.

**Comment by griff** [comment]
I have updated the site documentation with the solutions described here. Is it OK with you that I close this issue?

**Comment by NaLiJa** [comment]
Yes, thanks for the fix! Sorry for the slow response time. I have been on vacation, offline.
